### ISSUE TITLE
[Feature] Handle case where `contact_link` is missing

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_lever_source#25]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

It is possible for `contact_link` (and any other tables for that matter) to not exist in your WH even if it is selected in the Fivetran Connector Schema (it is a child table automatically synced through the `opportunity` endpoint). 

The package should be able to run successfully in this case

### How would you implement this feature?

Ideally, we totally avoid transformations related to `contact_link` -- here and in the transform package. 

## Option 1 
Dynamically disable model using `does_table_exist` macro we will be leveraging in https://github.com/fivetran/dbt_lever_source/issues/23

Pro: Best/most seamless option if we can make it work
Con: However, I am not 100% certain that this will work with the order of dbt's parsing/compilation.

## Option 2
Create empty table(s) if `contact_link` is not found a la our `union_data` macro

Pro: This is a relatively seamless option but 
Con: Will produce 1-2 empty tables in the user's WH 

## Option 3
Add `using_contact_link` to turn off all transformations related to contact_link 

Pro: Very straightforward to add
Con: May not work for Quickstart users, since the `contact_link` table may still be chosen in the connector schema tab

### Describe alternatives you've considered

see above

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance.
- [ ] No.

**Comment by fivetran-catfritz** [comment]
this is released, so closing out the issue!
