### ISSUE TITLE
Posting Tag Table may not necessarily exist, causes failure

### ISSUE THREAD

**Issue by nelsonauner** [fivetran/dbt_lever_source#4]
Lever integration is enabled and table `posting_tag` has ✔️ 
![image](https://user-images.githubusercontent.com/3402261/109426768-25c1fe00-79a4-11eb-91cf-1d8be358e012.png)

However table does not exist in target snowflake database - likely because we do not use posting tags? 

Causes error:
```
Database Error in model stg_lever__posting_tag_tmp (models/tmp/stg_lever__posting_tag_tmp.sql)
  002003 (42S02): SQL compilation error:
  Object 'FIVETRAN_ETL.LEVER.POSTING_TAG' does not exist or not authorized.
  compiled SQL at target/run/lever_source/models/tmp/stg_lever__posting_tag_tmp.sql
```

Possible solutions:
1. Create the table myself in snowflake with proper columns (as described [here](https://github.com/fivetran/dbt_lever_source/blob/47cb949859c4756b0f88c752f046f23e391c3dd1/models/src_lever.yml#L128-L136) in schema.yml) - this isn't a code fix, so I'd close this ticket
2. Open a PR against this package to enable manually toggling this off ? 
3. Open a PR against this package to smartly check if this table exists and do something (create temp empty table?) if the table does not exist

I am happy to do these, though I am on vacation for the next two weeks

**Comment by fivetran-kristin** [comment]
Hey @nelsonauner, thanks for raising this issue!  When you have this table configured to sync, but you don't have the table in your warehouse, it's due to not using the functionality in the source.  Do you know if you use posting tags in Lever?

As a quick-fix, you could test creating a posting tag in Lever to generate this table.

As a longer-term solution, we'll want to add functionality to manually turn this functionality off.  We can do this on our team over the next few sprints, or we're happy to review a PR if you want to do this.

cc: @fivetran-jamie

**Comment by nelsonauner** [comment]
@fivetran-kristin  - Correct, we're not posting tags in lever. 

I'd be happy to make a quick PR - what do you prefer between the below two options? 

1. Open a PR against this package to enable manually toggling this off 
2. Open a PR against this package to smartly check if this table exists and do something (create temp empty table?) if the table does not exist

**Comment by fivetran-kristin** [comment]
Thanks @nelsonauner !

Option 1 is our preferred approach.  Here's a quick overview of the steps needed to take and some examples:
1. Disable staging models, both stg and tmp.
2. Update README, under a new "Disabling Models" section.  Example [here](https://github.com/fivetran/dbt_jira_source#disabling-models).
2. Add variable to `dbt_project.yml` file, as an example. Default should be true. 

Example commits, [here](https://github.com/fivetran/dbt_jira_source/commit/0e07dbcdf55c2019e0ce5f503aafe99ba819e208) and [here](https://github.com/fivetran/dbt_jira_source/commit/64e340a3c32ef0e87d4abb9836751140f2eb4c89).

**Comment by fivetran-kristin** [comment]
Also, I assume you are using the model/transform package as well? 

If so, [here's another example commit you can reference](https://github.com/fivetran/dbt_jira/commit/32e8070b3cd8f195a2006a07c2faabd6578e4b94). The only new thing here is adding functionality to disable a portion of a model, which will need to be done for `lever__posting_enhanced`.

**Comment by nelsonauner** [comment]
Thank you for the helpful comments! I've opened a PR and am eager for feedback. I will also start work on the model/transform package as well.

**Comment by nelsonauner** [comment]
Thanks. I also didn't version up, hopefully you do that on your end somehow?
